language: java
jdk:
        - openjdk8
addons:
        sonarcloud:
                organization: lorenzomei
                token:
                        #secure: abf09675b7beaabb3463247e07cbf3062a3c0e55
script:
        - ant build
        - sonar-scanner
