language: java
jdk:
        - openjdk8
addons:
        sonarcloud:
                organization: lorenzomei
                token: e3a725e1511e60181587de39f6688934e4777502
                      
script:
        - ant build
        - sonar-scanner
